name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: List SSH keys (debug)
        run: ssh-add -l

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -vvv -tt -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/automation-aid
            git fetch origin main
            git reset --hard origin/main
            npm install
            npm run build
            sudo systemctl reload nginx
            exit
            EOF

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Deployment succeeded for automationaid! Way to go!"}' \
               "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Deployment failed for automationaid. Check GitHub Actions logs for details."}' \
               "${{ secrets.DISCORD_WEBHOOK }}"
