
name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          if [ -z "$SERVER_IP" ] || [ -z "$SERVER_USER" ]; then
            echo "Error: SERVER_IP or SERVER_USER is not defined in secrets."
            exit 1
          fi
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/automation-aid
            git fetch origin main
            git reset --hard origin/main
            npm install
            npm run build
            pm2 restart automation-aid || pm2 start npm --name "automation-aid" -- start
            sudo systemctl reload nginx
            echo "Clearing nginx cache..."
            sudo rm -rf /var/cache/nginx
            sudo mkdir /var/cache/nginx
            sudo chown -R www-data:www-data /var/cache/nginx
            sudo chmod -R 755 /var/cache/nginx
            sudo nginx -t && sudo systemctl restart nginx
            exit
          EOF

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Deployment succeeded for automationaid! Way to go Sava and Slav!"}' \
               "https://discord.com/api/webhooks/1341708827183157349/HouXP_cSD1s-BzC3OYlBq83lZZIRQVCLszWhPas3rpcZhrn08B2qM0_1ybzCJyIAy54z"

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Deployment failed for automationaid. Check GitHub Actions logs for details. Shit hit the fan yo!!"}' \
               "https://discord.com/api/webhooks/1341708827183157349/HouXP_cSD1s-BzC3OYlBq83lZZIRQVCLszWhPas3rpcZhrn08B2qM0_1ybzCJyIAy54z"
